### ISSUE TITLE
Simplify workflow by using $GITHUB_OUTPUT environment file 

### ISSUE THREAD

**Issue by vberlier** [willmcgugan/faqtory#13]
Currently the example workflow uses `read-file-action` to expose the suggestion to the step that creates the comment. However GitHub actions can do this natively using the `$GITHUB_OUTPUT` environment file https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

```yml
- name: Run Suggest
  id: suggest
  run: |
    echo 'content<<EOF' >> $GITHUB_OUTPUT
    faqtory suggest "${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
    echo 'EOF' >> $GITHUB_OUTPUT
```

Untested but I think that's how it would work.
